### PR TITLE
Implement mapping function config

### PR DESCRIPTION
**Pull request by manuelmiksche**
Mapping function config to modify the user entity

### CODE REVIEW

**Comment by felixkempf** [comment]
@manuelmiksche What's that for? Could you give an example?

**Comment by manuelmiksche** [comment]
We need to match and set the user language manually because the user language field does not contain a matchable language string.

Example function:

```
function ($user, $request, $response) {
                $language = 'en_EN';

                if (!empty($user->language)) {
                    $userLanguage = $user->language;
                    $userLanguage = substr($userLanguage, 0, 2);

                    $languageConfig = Configure::read('availableLanguages');
                    foreach ($languageConfig as $key => $val) {
                        if ($userLanguage === substr($key, 0, 2)) {
                            $language = $val;
                            break;
                        }
                    }
                }

                $user->language = $language;
            }
```

**Comment by felixkempf** [comment]
Then please add an explanation to this feature to the README

**Comment by manuelmiksche** [comment]
@felixkempf added the feature to the readme file.

**Comment by felixkempf** [comment]
I finally realized what bothers me. The name of the config key should be, what it essentially is. A `beforeSaveCallback`, because you can use it to change whatever you want right before the save. That's not only changing the format of the language code but also e.g. setting other fields etc.

What do you think @manuelmiksche ?

**Comment by manuelmiksche** [comment]
@felixkempf you're right. I'll change and push it to the branch.

**Review by felixkempf — APPROVED** [review]

**Pull request merged**
